site_name: Immac' 2025 - 26
site_url: https://bts-ciel-immac-laval.github.io

copyright: Copyright &copy; 2025 - 2026 Mathieu DOMER

nav:
  - BTS : 
    # - Calendrier de l'Avent : bts/00_calendrier_avent.md
    - Les gammes : bts/10_gammes.md
    - Stages : bts/20_stages.md
    # - Vidéos : bts/30_videos.md
    - Plus Plus : bts/99_plusplus.md
  - BTS 1 :
    - Projet Thelma : bts-1/10-projet-thelma.md
  #   - C'est pour bientôt ! : bts-1/00-waitforit.md
  #   - 01 - Premiers pas en C : bts-1/10-premiers-pas-en-c.md
    - 01 - Premiers programmes : bts-1/20-premiers-programmes.md
    - 02 - Boucles : bts-1/30-boucles.md
    - 03 - Fonctions :
      - Usage courant : bts-1/40-fonctions.md
  #     - Variables statiques : bts-1/41-fonctions.md
  #     - Récursivité : bts-1/42-fonctions.md
  #   - 05 - Pointeurs : bts-1/50-pointeurs.md
  #   - 06 - Tableaux : bts-1/60-tableaux.md
  #   - 07 - Chaînes de caractères : bts-1/70-strings.md
  #   - 08 - Les experts : bts-1/71-strings.md
  #   - 09 - Structures : bts-1/80-structures.md
  #   - 10 - Allocations dynamiques : bts-1/90-dynamic.md
  #   - 11 - Listes chaînées : bts-1/91-listes-chainees.md
  #   - 12 - POO : bts-1/100-poo-1.md
  #   - Maths x STI :
  #     - 01 - Algorithmique : bts-1/Maths x STI/10-algorithmique.md
  #     - 02 - Bases de données : bts-1/Maths x STI/20-bdd.md
  #     - 03 - Intégrales : bts-1/Maths x STI/30-integrales.md
  #     - 04 - Algorithme de Dijkstra : bts-1/Maths x STI/40-dijkstra.md
  - BTS 2 : 
    - 01 - Du C au C++ : bts-2/10-du-c-au-cpp.md
    - 02 - Premiers pas en POO : bts-2/01-poo-1.md
    - 03 - POO level 2 : bts-2/30-poo-2.md
    - 04 - POO ++ : bts-2/40-poo-3.md
    - Bataille navale : bts-2/80-battleships-1.md
    - Qt : 
      - Découverte : bts-2/90-qt-1.md
      - Premier projet : bts-2/90-qt-2.md
      - Exercices : bts-2/90-qt-3.md
  #     - Projet : bts-2/90-qt-4.md
  #   - Maths x STI :
  #     - 01 - Probabilités : bts-2/Maths x STI/10-probabilites.md
  #     - 02 - Valorisation de la donnée : bts-2/Maths x STI/20-excel-data-1.md
  - NSI : 
    - Coder à la maison : nsi/10_coder.md
    - S'entraîner : nsi/20_s-entrainer.md

theme:
  name: material
  language: fr
  features:
    - navigation.tabs
    - navigation.indexes
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Mode sombre
      primary: lime
      accent: indigo
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mode clair
      primary: lime
      accent: indigo
  logo: assets/f11_logo.png
  favicon: assets/f11_logo.png
extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf_viewer.min.css
  - stylesheets/extra.css
extra:
  consent:
    title: Consentement aux cookies
    description: >- 
      Nous utilisons des cookies pour reconnaître vos visites répétées et vos préférences, ainsi que pour mesurer l'efficacité de notre site et pour savoir si les utilisateurs trouvent ce qu'ils recherchent. Avec votre consentement, vous nous aidez à améliorer notre application.
  analytics:
    provider: google
    property: G-6C2DYFDCZV
plugins:
  - search
  - tags
markdown_extensions:
  - tables
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences :
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs
  - javascripts/main.js
